"""Regenerate the Lovelace card with the current alarm and banner entity IDs.

Reads ALARM_MESSAGES_NL and BANNER_MESSAGES_NL from the integration and
emits a grid card with one collapsing tile per non-SPARE code. Run from
the repo root:

    python tools/gen_card.py
"""

from __future__ import annotations

import re
import sys
import unicodedata
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "custom_components" / "leisure_pools"))

from messages import ALARM_MESSAGES_NL, BANNER_MESSAGES_NL  # noqa: E402

DEVICE_SLUG = "pool"


def slugify(value: str) -> str:
    value = unicodedata.normalize("NFKD", value)
    value = value.encode("ascii", "ignore").decode("ascii")
    value = value.lower()
    value = re.sub(r"[^a-z0-9]+", "_", value)
    return value.strip("_")


def entity_name(message: str) -> str:
    cleaned = " ".join(message.replace("\n", " ").split())
    if "|" in cleaned:
        _, _, cleaned = cleaned.partition("|")
        cleaned = cleaned.strip()
    return cleaned


def emit_tile(entity_id: str, lines: list[str]) -> None:
    lines.append(f"  - type: tile")
    lines.append(f"    entity: {entity_id}")
    lines.append(f"    grid_options:")
    lines.append(f"      columns: full")
    lines.append(f"      rows: 1")
    lines.append(f"    visibility:")
    lines.append(f"      - condition: state")
    lines.append(f"        entity: {entity_id}")
    lines.append(f'        state: "on"')
    lines.append(f"    hide_state: true")
    lines.append(f"    vertical: false")
    lines.append(f"    features_position: bottom")


def main() -> None:
    out: list[str] = []
    out.append("# Auto-generated by tools/gen_card.py - do not edit by hand.")
    out.append("# Shows every alarm and banner as a collapsing tile that only")
    out.append("# appears when the corresponding binary_sensor is on.")
    out.append("type: grid")
    out.append("cards:")

    sections: list[tuple[str, dict[int, str]]] = [
        ("Alarms", ALARM_MESSAGES_NL),
        ("Process banners", BANNER_MESSAGES_NL),
    ]

    for title, mapping in sections:
        out.append(f"  # --- {title} ---")
        for code, message in sorted(mapping.items()):
            if "SPARE" in message.upper():
                continue
            slug = slugify(entity_name(message))
            entity_id = f"binary_sensor.{DEVICE_SLUG}_{slug}"
            out.append(f"  # code {code}: {message}")
            emit_tile(entity_id, out)

    output_path = REPO_ROOT / "lovelace" / "leisure-pool-card.yaml"
    output_path.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"Wrote {output_path}")


if __name__ == "__main__":
    main()
